### PR TITLE
Duplicated note

### PR DESCRIPTION
**Pull request by administrator2992**
in line 98 and 100, is it duplicated or wrong one ?

### CODE REVIEW

**Comment by JiahangXu** [comment]
Thanks for the PR! The note is duplicated. We will directly remove it.

**Comment by administrator2992** [comment]
yes, i can do it

**Comment by administrator2992** [comment]
i think the duplicated note is deleted, please review again

**Review by JiahangXu — APPROVED** [review]

**Comment by administrator2992** [comment]
Sorry, i not see a change in main branch

**Pull request merged**
